#!/usr/bin/env bash
# PreToolUse guard for Edit/Write: block edits to the generated SPA files that are
# owned by Axis's deploy-remote Action (never hand-edited here).
# Exits 2 with a clear reason on stderr to block; exits 0 otherwise.
set -euo pipefail

raw="$(cat)"

if command -v jq >/dev/null 2>&1; then
  path="$(printf '%s' "$raw" | jq -r '.tool_input.file_path // ""')"
else
  # Conservative fallback: scan the whole raw payload.
  path="$raw"
fi

# Generated set: anything under public/_app/, plus these top-level SPA artifacts.
gen='(public/_app/|public/index\.html|public/service-worker\.js|public/manifest\.webmanifest|public/icon\.svg|public/icon-192\.png|public/icon-512\.png|public/apple-touch-icon\.png|public/favicon\.png|public/version\.json)'
if printf '%s' "$path" | grep -Eq "$gen"; then
  echo "guard-generated: blocked - generated by Axis's deploy-remote Action; re-run that action instead. Hand-owned files: welcome/imprint/privacy/terms .html, style.css, _headers, worker.js, wrangler.jsonc." >&2
  exit 2
fi

exit 0
